#ifndef PRINTOUT_H_INCLUDED
#define PRINTOUT_H_INCLUDED

enum
{
    SPEEDTEST_ERROR_UNDEFINED = -13,
    SPEEDTEST_ERROR_WSAERR,
    SPEEDTEST_ERROR_SOCKETERR,
    SPEEDTEST_ERROR_NORECOGLINK,
    SPEEDTEST_ERROR_NOCONNECTION,
    SPEEDTEST_ERROR_INVALIDSUB,
    SPEEDTEST_ERROR_NONODES,
    SPEEDTEST_ERROR_NORESOLVE,
    SPEEDTEST_ERROR_RETEST,
    SPEEDTEST_ERROR_NOSPEED,
    SPEEDTEST_ERROR_UNRECOGFILE,
    SPEEDTEST_ERROR_SUBFETCHERR,
    SPEEDTEST_ERROR_GEOIPERR,
    SPEEDTEST_ERROR_NONE
};

// Message IDs for printMsg(). Protocol-specific "found <proto>" messages were
// removed when protocol parsing moved to the mihomo kernel; only source-type
// hints (sub / local file / upload / multilink) and flow messages remain.
enum
{
    SPEEDTEST_MESSAGE_WELCOME = 1,
    SPEEDTEST_MESSAGE_FOUNDSUB,
    SPEEDTEST_MESSAGE_GOTSERVER,
    SPEEDTEST_MESSAGE_STARTPING,
    SPEEDTEST_MESSAGE_GOTPING,
    SPEEDTEST_MESSAGE_STARTSPEED,
    SPEEDTEST_MESSAGE_GOTSPEED,
    SPEEDTEST_MESSAGE_GOTRESULT,
    SPEEDTEST_MESSAGE_TRAFFIC,
    SPEEDTEST_MESSAGE_PICSAVING,
    SPEEDTEST_MESSAGE_PICSAVED,
    SPEEDTEST_MESSAGE_GROUP,
    SPEEDTEST_MESSAGE_FETCHSUB,
    SPEEDTEST_MESSAGE_BEGIN,
    SPEEDTEST_MESSAGE_FOUNDLOCAL,
    SPEEDTEST_MESSAGE_PARSING,
    SPEEDTEST_MESSAGE_FOUNDUPD,
    SPEEDTEST_MESSAGE_PICDATA,
    SPEEDTEST_MESSAGE_STARTGPING,
    SPEEDTEST_MESSAGE_GOTGPING,
    SPEEDTEST_MESSAGE_STARTGEOIP,
    SPEEDTEST_MESSAGE_GOTGEOIP,
    SPEEDTEST_MESSAGE_MULTILINK,
    SPEEDTEST_MESSAGE_PICSAVINGMULTI,
    SPEEDTEST_MESSAGE_PICSAVEDMULTI,
    SPEEDTEST_MESSAGE_STARTUPD,
    SPEEDTEST_MESSAGE_GOTUPD,
    SPEEDTEST_MESSAGE_STARTNAT,
    SPEEDTEST_MESSAGE_GOTNAT,
    SPEEDTEST_MESSAGE_EOF
};

#endif // PRINTOUT_H_INCLUDED
